//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeocachingTourPlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileOperations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileOperations() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeocachingTourPlanner.Properties.FileOperations", typeof(FileOperations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created new ratingprofile database ähnelt.
        /// </summary>
        internal static string CreatedNewRatingprofileDatabase {
            get {
                return ResourceManager.GetString("CreatedNewRatingprofileDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created new route database ähnelt.
        /// </summary>
        internal static string CreatedNewRouteDatabase {
            get {
                return ResourceManager.GetString("CreatedNewRouteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created new routingprofile database ähnelt.
        /// </summary>
        internal static string CreatedNewRoutingprofileDatabase {
            get {
                return ResourceManager.GetString("CreatedNewRoutingprofileDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export route as track ähnelt.
        /// </summary>
        internal static string ExportRouteAsTrack {
            get {
                return ResourceManager.GetString("ExportRouteAsTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import geocaches ähnelt.
        /// </summary>
        internal static string ImportGeocaches {
            get {
                return ResourceManager.GetString("ImportGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing geocaches.. ähnelt.
        /// </summary>
        internal static string ImportingGeocaches {
            get {
                return ResourceManager.GetString("ImportingGeocaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed importing geocaches ähnelt.
        /// </summary>
        internal static string ImportingGeocachesFailed {
            get {
                return ResourceManager.GetString("ImportingGeocachesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Started importing geocaches ähnelt.
        /// </summary>
        internal static string ImportingGeocachesStarted {
            get {
                return ResourceManager.GetString("ImportingGeocachesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully imported geocaches ähnelt.
        /// </summary>
        internal static string ImportingGeocachesSuccessful {
            get {
                return ResourceManager.GetString("ImportingGeocachesSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import OSM Data ähnelt.
        /// </summary>
        internal static string ImportOSMData {
            get {
                return ResourceManager.GetString("ImportOSMData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New File ähnelt.
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new, empty geocache database ähnelt.
        /// </summary>
        internal static string NewGeocacheDatabase {
            get {
                return ResourceManager.GetString("NewGeocacheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new, empty ratingprofile database ähnelt.
        /// </summary>
        internal static string NewRatingprofileDatabase {
            get {
                return ResourceManager.GetString("NewRatingprofileDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new, empty route database ähnelt.
        /// </summary>
        internal static string NewRouteDatabase {
            get {
                return ResourceManager.GetString("NewRouteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new RouterDB file ähnelt.
        /// </summary>
        internal static string NewRouterDBFile {
            get {
                return ResourceManager.GetString("NewRouterDBFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new, empty routingprofile database ähnelt.
        /// </summary>
        internal static string NewRoutingprofileDatabase {
            get {
                return ResourceManager.GetString("NewRoutingprofileDatabase", resourceCulture);
            }
        }
    }
}
